# Generated by Django 4.1 on 2022-09-10 07:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('preview', models.ImageField(default=None, upload_to='uploads/preview/')),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(default=None, max_length=255)),
                ('file', models.FileField(default=None, upload_to=store.models.directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='SystemRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128)),
                ('os', models.CharField(default=None, max_length=128)),
                ('cpu', models.CharField(default=None, max_length=128)),
                ('ram', models.CharField(default=None, max_length=128)),
                ('network', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('video_card', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('disk_space', models.CharField(default=None, max_length=128)),
                ('description', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to='store.game')),
                ('games', models.ManyToManyField(blank=True, related_name='games', to='store.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='media',
            field=models.ManyToManyField(to='store.media'),
        ),
        migrations.AddField(
            model_name='game',
            name='sys_req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.systemrequirements'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(to='store.tag'),
        ),
    ]
