# Generated by Django 4.1 on 2022-09-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='media',
            field=models.ManyToManyField(blank=True, to='store.media'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, to='store.tag'),
        ),
    ]
