# Generated by Django 4.1 on 2022-09-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_game_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
    ]
