# Generated by Django 4.1 on 2022-09-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sys_req',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.systemrequirements'),
        ),
    ]
