# Generated by Django 4.1 on 2022-09-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_game_sys_req'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemrequirements',
            name='description',
        ),
        migrations.RemoveField(
            model_name='systemrequirements',
            name='network',
        ),
    ]
