# Generated by Django 4.1 on 2022-09-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_systemrequirements_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrequirements',
            name='disk_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemrequirements',
            name='ram',
            field=models.IntegerField(default=0),
        ),
    ]
