# Generated by Django 4.1 on 2022-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_game_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.AddConstraint(
            model_name='categories',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_Categories'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
